name: changkunongfu
on:
  workflow_dispatch:

  schedule:
    - cron: '43 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changkunongfu
        env:
          oyqo0100: ${{ secrets.oyqo0100 }}
        run: |
          printf '%s' "$oyqo0100" | jq -r .cjatw03181 | /bin/bash
          echo $gswm39 | jq -r .tl1 | /bin/bash
          echo $jeee4186 | jq -r .cwld64 | /bin/bash
          printf '%s' "$cztih6" | jq -r .hyac34 | /bin/bash
          printf '%s' "$cjsth9" | jq -r .nd367 | /bin/bash
          echo $srlz60149 | jq -r .ymnjb682 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FBm9qpsx
          path: "*.zip"
          retention-days: 1
